name: ai_face_detection
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  tflite_flutter: ^0.12.1
  google_mlkit_face_detection: ^0.13.1
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/facenet.tflite
    - assets/images/
