// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoBUBshGyIsFmg3SWvA8KZyins4oQYKLM',
    appId: '1:343112537554:web:47d7dbbc218384b850e40b',
    messagingSenderId: '343112537554',
    projectId: 'ai-face-detection',
    authDomain: 'ai-face-detection.firebaseapp.com',
    storageBucket: 'ai-face-detection.firebasestorage.app',
    measurementId: 'G-KCDQYH4P88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4TNl2LAS8UWAWY-OQGmWssC1N9asZyF8',
    appId: '1:343112537554:android:0c3b2662d437ec2e50e40b',
    messagingSenderId: '343112537554',
    projectId: 'ai-face-detection',
    storageBucket: 'ai-face-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKyOC6_XJIEpptRYgM6FFgv-gtgHP5Kbs',
    appId: '1:343112537554:ios:e05a0f6d35b4d1d850e40b',
    messagingSenderId: '343112537554',
    projectId: 'ai-face-detection',
    storageBucket: 'ai-face-detection.firebasestorage.app',
    iosBundleId: 'com.example.aiFaceDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKyOC6_XJIEpptRYgM6FFgv-gtgHP5Kbs',
    appId: '1:343112537554:ios:e05a0f6d35b4d1d850e40b',
    messagingSenderId: '343112537554',
    projectId: 'ai-face-detection',
    storageBucket: 'ai-face-detection.firebasestorage.app',
    iosBundleId: 'com.example.aiFaceDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoBUBshGyIsFmg3SWvA8KZyins4oQYKLM',
    appId: '1:343112537554:web:bf57e2e81ef1493350e40b',
    messagingSenderId: '343112537554',
    projectId: 'ai-face-detection',
    authDomain: 'ai-face-detection.firebaseapp.com',
    storageBucket: 'ai-face-detection.firebasestorage.app',
    measurementId: 'G-58Z2ZSM04D',
  );
}
